name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  get: 4.6.6
  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/aset/images/
    - lib/aset/logo/
    - lib/aset/product/
  uses-material-design: true
